### ISSUE TITLE
changed-files workflow can fail if number of changed files is too large

### ISSUE THREAD

**Issue by wence-** [rapidsai/shared-workflows#251]
Programmatic updates to large repos (e.g. https://github.com/rapidsai/cudf/actions/runs/11382819285/job/31667149096?pr=16685) can cause many file to be lists in the changed-files list.

This can overflow the shell's argument list limit, causing the workflow to fail.

**Comment by jameslamb** [comment]
@KyleFromNVIDIA could you take a look at this?

Posting the logs since those CI logs will eventually expire:

> *Run (echo -n "transformed-output="; jq -c -n "env.CHANGED_FILES | fromjson | $TRANSFORM_EXPR") | tee --append "$GITHUB_OUTPUT"*
> *Error: An error occurred trying to start process '/usr/bin/bash' with working directory '/home/runner/work/cudf/cudf'. Argument list too long*

**Comment by KyleFromNVIDIA** [comment]
The error message is misleading: it's not the argument list that's overflowing, but rather the environment variable memory block. Nevertheless, the concept is the same.

We can write the JSON to a file instead. I'll go ahead and do that.
